---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/activities":
    post:
      summary: create activity
      tags:
      - Activities
      responses:
        '201':
          description: successful
  "/api/v1/activities/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    delete:
      summary: delete activity
      tags:
      - Activities
      responses:
        '204':
          description: no content
  "/api/v1/days":
    get:
      summary: list days
      tags:
      - Days
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                no_days: {}
                days:
                  value:
                  - id: 4
                    date: '2023-03-28T22:00:00.000Z'
                    created_at: '2023-03-29T14:10:43.226Z'
                    updated_at: '2023-03-29T14:10:43.226Z'
                  - id: 2
                    date: '2023-04-04T22:00:00.000Z'
                    created_at: '2023-04-05T19:41:08.528Z'
                    updated_at: '2023-04-05T19:41:08.528Z'
    post:
      summary: create day
      tags:
      - Days
      responses:
        '201':
          description: created
          content:
            application/json:
              examples:
                day:
                  value:
                    id: 4
                    date: '2023-03-28T22:00:00.000Z'
                    created_at: '2023-03-29T14:10:43.226Z'
                    updated_at: '2023-03-29T14:10:43.226Z'
        '422':
          description: unprocessable entity
          content:
            application/json:
              examples:
                date:
                  value:
                    date:
                    - has already been taken
  "/api/v1/days/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show day
      tags:
      - Days
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                day:
                  value:
                    id: 4
                    date: '2023-03-28T22:00:00.000Z'
                    created_at: '2023-03-29T14:10:43.226Z'
                    updated_at: '2023-03-29T14:10:43.226Z'
    delete:
      summary: delete day
      tags:
      - Days
      responses:
        '204':
          description: no content
        '404':
          description: not found
  "/api/v1/hydrations":
    post:
      summary: create hydration
      tags:
      - Hydrations
      parameters: []
      responses:
        '201':
          description: created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                cups:
                  type: integer
  "/api/v1/hydrations/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    patch:
      summary: update hydration
      tags:
      - Hydrations
      parameters:
      - name: id
        in: path
        required: true
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                cups:
                  type: integer
    put:
      summary: update hydration
      tags:
      - Hydrations
      parameters:
      - name: id
        in: path
        required: true
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                cups:
                  type: integer
    delete:
      summary: delete hydration
      tags:
      - Hydrations
      responses:
        '204':
          description: no content
  "/api/v1/sleeps":
    post:
      summary: create sleep
      tags:
      - Sleeps
      responses:
        '201':
          description: created
  "/api/v1/sleeps/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    delete:
      summary: delete sleep
      tags:
      - Sleeps
      responses:
        '204':
          description: no content
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
