---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/activities":
    post:
      summary: create activity
      tags:
      - Activities
      responses:
        '200':
          description: successful
  "/api/v1/activities/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    delete:
      summary: delete activity
      tags:
      - Activities
      responses:
        '200':
          description: successful
  "/api/v1/days":
    get:
      summary: list days
      tags:
      - Days
      responses:
        '200':
          description: successful
    post:
      summary: create day
      tags:
      - Days
      responses:
        '201':
          description: created
          content:
            application/json:
              examples:
                day:
                  value:
                    id: 4
                    date: '2023-03-28T22:00:00.000Z'
                    created_at: '2023-03-29T14:10:43.226Z'
                    updated_at: '2023-03-29T14:10:43.226Z'
  "/api/v1/days/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show day
      tags:
      - Days
      responses:
        '200':
          description: successful
    delete:
      summary: delete day
      tags:
      - Days
      responses:
        '200':
          description: successful
  "/api/v1/hydrations":
    post:
      summary: create hydration
      tags:
      - Hydrations
      responses:
        '200':
          description: successful
  "/api/v1/hydrations/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    patch:
      summary: update hydration
      tags:
      - Hydrations
      responses:
        '200':
          description: successful
    put:
      summary: update hydration
      tags:
      - Hydrations
      responses:
        '200':
          description: successful
    delete:
      summary: delete hydration
      tags:
      - Hydrations
      responses:
        '200':
          description: successful
  "/api/v1/sleeps":
    post:
      summary: create sleep
      tags:
      - Sleeps
      responses:
        '200':
          description: successful
  "/api/v1/sleeps/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    delete:
      summary: delete sleep
      tags:
      - Sleeps
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
